function load_unitconv(ringmode)

dir = fileparts(mfilename('fullpath'));
cd(dir);
ini_file = fullfile(dir, '..', 'aphla', 'machines', ringmode, 'unitconv.ini');


fprintf('Loading unit conversions to file %s\n', ini_file);

f = fopen(ini_file, 'w');
fprintf(f, '# Unit conversions generated by load_unitconv.m.\n\n');

quad_families = families_from_prefix('Q', {'QUAD_'});
sext_families = families_from_prefix('S', {'SEXT_', 'SQUAD'});

for i = 1:length(quad_families)
    write_multipole_section(f, quad_families{i}, 'b1', 'm^-2');
end

for i = 1:length(sext_families)
    write_multipole_section(f, sext_families{i}, 'b2', 'm^-3');
end

coeffs = get_poly_coeffs('BEND', 1, false);
write_section(f, 'BEND', 'b0', 'A', 'rad', coeffs);
write_section(f, 'BPM', 'x', 'mm', 'm', [0, 0, 0, 0.001, 0]);
write_section(f, 'BPM', 'y', 'mm', 'm', [0, 0, 0, 0.001, 0]);

% If corrector magnets are windings on a sextupole, their AT Index is that
% of the sextupole.  We have to reverse that.
sext_data = getfamilydata('SEXT_');
sext_indices = sext_data.AT.ATIndex;

hcor = getfamilydata('HCM');
for i = 1:length(hcor.DeviceList)
    coeffs = get_poly_coeffs('HCM', i, false);
    hcor_index = hcor.AT.ATIndex(i);
    if any(hcor_index == sext_indices)
        hcor_index = hcor_index + 1;
    end
    write_section(f, num2str(hcor_index), 'b0', 'A', 'rad', coeffs);
end

vcor = getfamilydata('VCM');
for i = 1:length(vcor.DeviceList)
    coeffs = get_poly_coeffs('VCM', i, false);
    vcor_index = vcor.AT.ATIndex(i);
    if any(vcor_index == sext_indices)
        vcor_index = vcor_index + 2;
    end
    write_section(f, num2str(vcor_index), 'b0', 'A', 'rad', coeffs);
end

fclose(f);

end


function families = families_from_prefix(prefix, exclude)
    families = {};
    familylist = cellstr(getfamilylist());
    for i = 1:length(familylist)
        if strncmp(familylist{i}, prefix, 1)
            families{end + 1} = familylist{i};
        end
    end
    families = setdiff(families, exclude);
end


function write_section(file, group, field, src_unit, dst_unit, coeffs)

    fprintf(file, '[%s(%s)]\n', group, field);
    fprintf(file, 'dst_unit_sys: phy\n');
    fprintf(file, 'src_unit: %s\n', src_unit);
    fprintf(file, 'dst_unit: %s\n', dst_unit);
    fprintf(file, 'polynomial: %0.15f %0.15f %0.15f %0.15f %0.15f\n', coeffs);
    fprintf(file, 'groups: %s\n', group);
    fprintf(file, 'field: %s\n\n', field);

end


function write_multipole_section(f, family, field, units)
    a = hw2physics(family, 'Monitor', 100);
    if all(a / a(1) == 1)  % All the magnets in the family have the same
                           % unit conversion.
        coeffs = get_poly_coeffs(family, 1, false);
        write_section(f, family, field', 'A', units, coeffs);
    else  % Need unit conversion data for each magnet in the family.
        irregular_mags = getfamilydata(family);
        for j = 1:length(irregular_mags.DeviceList)
            coeffs = get_poly_coeffs(family, j, false);
            q_index = irregular_mags.AT.ATIndex(j);
            write_section(f, num2str(q_index), field, 'A', units, coeffs);
        end
    end
end


function coeffs = get_poly_coeffs(family, devices, plot_graph)

    cal_data = get_cal_data(family);
    current_max = max(cal_data.current);
    if current_max < 0
        current_max = 0;
    end
    current_min = min(cal_data.current);
    if current_min > 0
        current_min = 0;
    end
    range = current_min:1:current_max;
    cal = [];
    for j = 1:length(range)
        cal(j) = hw2physics(family, 'Monitor', range(j), devices);
    end
    coeffs = polyfit(range, cal, 4);
    disp(coeffs);
    
    if plot_graph
        plot(cal_data.current, cal_data.field, 'x');
        hold on
        brho = 10.069;
        f = @(x) coeffs(1) .* x .^4 + coeffs(2) .* x .^3 + coeffs(3) .* x .^2 + coeffs(4) .* x + coeffs(5);
        plot(range, f(range) * brho, 'r');
        plot(range, cal * brho, 'g');
    end
   
end


function cal_data = get_cal_data(famname)

    global calibration_data;

    disp(famname);
    fd = getfamilydata(famname);
    chan = fd.Monitor.ChannelNames(1,:);
    index = calibration_lookup2(chan);
    cal_data = calibration_data{index};
    disp(cal_data);
    
end
